apiVersion: v1
entries:
  rocky:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-01-09T09:35:50.299514-05:00"
    description: A Helm chart for Kubernetes
    digest: d5306fc06dd2b4aaf5dd9749ac02db5789e13a909f3e15529efd8f5ef1eb1e9c
    name: rocky
    type: application
    urls:
    - docs/rocky-1.0.0.tgz
    version: 1.0.0
generated: "2024-01-09T09:35:50.298068-05:00"
